### ISSUE TITLE
About Ricci Curvature Pre-transform

### ISSUE THREAD

**Issue by cjissmart** [yeze16159/CurvGN#2]
I notice some operations which process ricci curvature in ConvCurv.py before CurvGN is called. However, there aren't corresponding interpretations in the paper. Could you account for the two operations with the red underlines in the figure? The first operation seemly is normalization. The second operation is softmax, to prevent a numerical explosion. Is it properly for ricci curvature as MLP's input? As usual, softmax is used for non-negative numbers. However, most of data.w_mul are negative here.
![微信截图_20200612230527](https://user-images.githubusercontent.com/37531166/84517390-d64a7d80-ad01-11ea-852d-6e25d8a0d4a3.png)

**Comment by cjissmart** [comment]
> t

As usual, softmax is used for non-negative numbers. However, most of data.w_mul are negative.

**Comment by yeze16159** [comment]
Thank you for pointing it out. Since the reweighting parameter is trying to find the discriminant information.  I update the code to make it all positive (Positive or negative is not important, as long as the input has the information and MLP will learn to use such information to reweight message). The reason for making them all in the same sign is to let MLP easier to learn the information.  The softmax part is deleted.
